### ISSUE TITLE
Fetching message bodies should be easier

### ISSUE THREAD

**Issue by jgillich** [pipedrive/inbox#52]
First, let me thank you for all your great work. I am currently building a webmail client and it is just amazing to see that you already wrote all the tools I need.

One thing that could be improved IMHO is the retrieval of message bodies. While `createMessageStream` works fine, in my case I always need the full string in order to output JSON, thus the pipe has no advantages. A function that (asynchronously) returns the full body as a string would be much easier to use. Even better would be if it would only return the text without the header fields like `Subject` (not entirely sure how these are called).
Or, what about a variant of `fetchData` that includes the message body?

If you agree with me, I could work on a patch. I have to admit I don't know much about IMAP, but I am willing to learn. :)

**Comment by jcuenod** [comment]
I found [mailparser](https://nodemailer.com/extras/mailparser/) to make this incredibly easy:

    const simpleParser = require('mailparser').simpleParser;

    simpleParser( client.createMessageStream(message.UID) ).then((mailObject) => {
       console.log(mailObject)
    })
