### ISSUE TITLE
"new" event not triggering?

### ISSUE THREAD

**Issue by DeviaVir** [pipedrive/inbox#70]
After selecting the correct mailbox, listing the messages inside (correctly) and then executing following code:

```
client.on("new", function(message){
    console.log("New incoming message " + message.title);
});
```

And sending a new message does not trigger this console.log

**Comment by sentient** [comment]
I'm guessing that the order when you register for new mail is important. Set up the callback before you make the call to client.connect();

This works for me
```
  var client = _getConnection();
  client.on('connect, function(){
   ...
  });
  client.on('new', function(){
    ...
  });

  client.connect();
```

I used to had the `client.on('new'...` inside the `connect` callback, and that does not work.

**Comment by jcuenod** [comment]
I think it's worth adding a note about this in the readme.
Thanks @masashiGMS!
