### ISSUE TITLE
Can we implement archive?

### ISSUE THREAD

**Issue by AP25** [pipedrive/inbox#97]
Hi Andris,
How can we implement archive using inbox module.When we archive mail from Inbox it disappears from Inbox but it is present in all-mail mailbox.Is there any label available to add/remove that mail from only Inbox mailbox or any method is available for archiving mails of inbox(to make it disappear from  Inbox folder).

Thanks in advance!!

**Comment by AVVS** [comment]
move message to all mail folder, it removes it from any other folder

**Comment by AP25** [comment]
Hi AVVS ,
Thank you!! It helps me to implement archive.
